// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    *@ngdoc function
    * @name snowApp.controller:CourseExamplesMapGooglemapcontrollerCtrl
    * @description
    * # CourseExamplesMapGooglemapcontrollerCtrl
    * Controller of the snowApp
   */
  angular.module('snowApp').controller('CourseExamplesMapGooglemapcontrollerCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma', 'test', 'test2', 'test3', 'test5'];
  });

}).call(this);

//# sourceMappingURL=googlemapcontroller.map
