// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc service
    * @name snowApp.course/manage/courseservice
    * @description
    * # course/manage/courseservice
    * Service in the snowApp.
   */
  angular.module('snowApp').service('CourseManageCourseservice', function($http, $q, i18n) {
    var buildFunction, url, urls, _i, _len, _results;
    urls = ['/course/fetchCourses', '/course/fetchCharpters', '/course/fetchSections'];
    buildFunction = function(url) {
      var methodName;
      methodName = url.split('/')[2];
      return this[methodName] = function() {
        var deferred;
        deferred = $q.defer();
        return $http({
          method: 'GET',
          url: url
        }).success(function(data) {
          return deferred.resolve(data);
        }).error(function() {
          return deferred.reject(i18n['error_can_not_receive_data']);
        });
      };
    };
    _results = [];
    for (_i = 0, _len = urls.length; _i < _len; _i++) {
      url = urls[_i];
      _results.push(buildFunction.call(this, url));
    }
    return _results;
  });

}).call(this);

//# sourceMappingURL=courseservice.map
