// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /*
   * @ngdoc overview
   * @name snowApp
   * @description
   * # snowApp
   *
   * Main module of the application.
   */
  angular.module('snowApp', ['ngAnimate', 'ngCookies', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch', 'ngGrid', 'i18n']).config(function($routeProvider, i18nProvider) {
    return $routeProvider.when('/', {
      templateUrl: i18nProvider.parseUrl('/views/course/manage/listcourses.html'),
      controller: 'CourseManageListCoursesCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);

//# sourceMappingURL=app.course.map
