// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Controller: CourseManageListcoursesCtrl', function() {
    var CourseManageListcoursesCtrl, scope;
    beforeEach(module('snowApp'));
    CourseManageListcoursesCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return CourseManageListcoursesCtrl = $controller('CourseManageListcoursesCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

//# sourceMappingURL=listcourses.map
