// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Controller: CourseManageManagecontrollerCtrl', function() {
    var CourseManageManagecontrollerCtrl, scope;
    beforeEach(module('snowApp'));
    CourseManageManagecontrollerCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return CourseManageManagecontrollerCtrl = $controller('CourseManageManagecontrollerCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

//# sourceMappingURL=managecontroller.map
