// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name snowApp.controller:AboutCtrl
   * @description
   * # AboutCtrl
   * Controller of the snowApp
   */
  angular.module('snowApp').controller('AboutCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

//# sourceMappingURL=about.map
