// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name snowApp.controller:MainCtrl
   * @description
   * # MainCtrl
   * Controller of the snowApp
   */
  angular.module('snowApp').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

//# sourceMappingURL=main.map
