// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
   * @ngdoc directive
   * @name snowApp.directive:i18nDirective
   * @description
   * # i18nDirective
   */
  console.log("Excute i18nDirective");

  angular.module('snowApp').directive('i18n', function(i18n) {
    return {
      restrict: 'EA',
      link: function(scope, element, attrs) {
        return element.text(i18n[attrs['i18n']]);
      }
    };
  });

}).call(this);

//# sourceMappingURL=i18nDirective.map
