package com.pairwinter.snow.base.enumerably;

/**
 * Created by damon on 14-7-21.
 */
public enum TimeZoneSnow {
    Pacific_Niue("Pacific/Niue","( GMT -11:00)Niue Time(Pacific/Niue)"),
    Pacific_Pago_Pago("Pacific/Pago_Pago","( GMT -11:00)Samoa Standard Time(Pacific/Pago_Pago)"),
    Pacific_Honolulu("Pacific/Honolulu","( GMT -10:00)Hawaii Standard Time(Pacific/Honolulu)"),
    Pacific_Johnston("Pacific/Johnston","( GMT -10:00)Hawaii Standard Time(Pacific/Johnston)"),
    Pacific_Rarotonga("Pacific/Rarotonga","( GMT -10:00)Cook Is. Time(Pacific/Rarotonga)"),
    Pacific_Tahiti("Pacific/Tahiti","( GMT -10:00)Tahiti Time(Pacific/Tahiti)"),
    Pacific_Marquesas("Pacific/Marquesas","( GMT -9:00)Marquesas Time(Pacific/Marquesas)"),
    America_Anchorage("America/Anchorage","( GMT -9:00)Alaska Standard Time(America/Anchorage)"),
    Pacific_Gambier("Pacific/Gambier","( GMT -9:00)Gambier Time(Pacific/Gambier)"),
    America_Los_Angeles("America/Los_Angeles","( GMT -8:00)Pacific Standard Time(America/Los_Angeles)"),
    America_Tijuana("America/Tijuana","( GMT -8:00)Pacific Standard Time(America/Tijuana)"),
    America_Vancouver("America/Vancouver","( GMT -8:00)Pacific Standard Time(America/Vancouver)"),
    America_Whitehorse("America/Whitehorse","( GMT -8:00)Pacific Standard Time(America/Whitehorse)"),
    Pacific_Pitcairn("Pacific/Pitcairn","( GMT -8:00)Pitcairn Standard Time(Pacific/Pitcairn)"),
    America_Dawson_Creek("America/Dawson_Creek","( GMT -7:00)Mountain Standard Time(America/Dawson_Creek)"),
    America_Denver("America/Denver","( GMT -7:00)Mountain Standard Time(America/Denver)"),
    America_Edmonton("America/Edmonton","( GMT -7:00)Mountain Standard Time(America/Edmonton)"),
    America_Hermosillo("America/Hermosillo","( GMT -7:00)Mountain Standard Time(America/Hermosillo)"),
    America_Mazatlan("America/Mazatlan","( GMT -7:00)Mountain Standard Time(America/Mazatlan)"),
    America_Phoenix("America/Phoenix","( GMT -7:00)Mountain Standard Time(America/Phoenix)"),
    America_Yellowknife("America/Yellowknife","( GMT -7:00)Mountain Standard Time(America/Yellowknife)"),
    America_Belize("America/Belize","( GMT -6:00)Central Standard Time(America/Belize)"),
    America_Chicago("America/Chicago","( GMT -6:00)Central Standard Time(America/Chicago)"),
    America_Costa_Rica("America/Costa_Rica","( GMT -6:00)Central Standard Time(America/Costa_Rica)"),
    America_El_Salvador("America/El_Salvador","( GMT -6:00)Central Standard Time(America/El_Salvador)"),
    America_Guatemala("America/Guatemala","( GMT -6:00)Central Standard Time(America/Guatemala)"),
    America_Managua("America/Managua","( GMT -6:00)Central Standard Time(America/Managua)"),
    America_Mexico_City("America/Mexico_City","( GMT -6:00)Central Standard Time(America/Mexico_City)"),
    America_Regina("America/Regina","( GMT -6:00)Central Standard Time(America/Regina)"),
    America_Tegucigalpa("America/Tegucigalpa","( GMT -6:00)Central Standard Time(America/Tegucigalpa)"),
    America_Winnipeg("America/Winnipeg","( GMT -6:00)Central Standard Time(America/Winnipeg)"),
    Pacific_Easter("Pacific/Easter","( GMT -6:00)Easter Is. Time(Pacific/Easter)"),
    Pacific_Galapagos("Pacific/Galapagos","( GMT -6:00)Galapagos Time(Pacific/Galapagos)"),
    America_Bogota("America/Bogota","( GMT -5:00)Colombia Time(America/Bogota)"),
    America_Cayman("America/Cayman","( GMT -5:00)Eastern Standard Time(America/Cayman)"),
    America_Grand_Turk("America/Grand_Turk","( GMT -5:00)Eastern Standard Time(America/Grand_Turk)"),
    America_Guayaquil("America/Guayaquil","( GMT -5:00)Ecuador Time(America/Guayaquil)"),
    America_Havana("America/Havana","( GMT -5:00)Cuba Standard Time(America/Havana)"),
    America_Iqaluit("America/Iqaluit","( GMT -5:00)Eastern Standard Time(America/Iqaluit)"),
    America_Jamaica("America/Jamaica","( GMT -5:00)Eastern Standard Time(America/Jamaica)"),
    America_Lima("America/Lima","( GMT -5:00)Peru Time(America/Lima)"),
    America_Montreal("America/Montreal","( GMT -5:00)Eastern Standard Time(America/Montreal)"),
    America_Nassau("America/Nassau","( GMT -5:00)Eastern Standard Time(America/Nassau)"),
    America_New_York("America/New_York","( GMT -5:00)Eastern Standard Time(America/New_York)"),
    America_Panama("America/Panama","( GMT -5:00)Eastern Standard Time(America/Panama)"),
    America_Port_au_Prince("America/Port-au-Prince","( GMT -5:00)Eastern Standard Time(America/Port-au-Prince)"),
    America_Toronto("America/Toronto","( GMT -5:00)Eastern Standard Time(America/Toronto)"),
    America_Caracas("America/Caracas","( GMT -4:00)Venezuela Time(America/Caracas)"),
    America_Anguilla("America/Anguilla","( GMT -4:00)Atlantic Standard Time(America/Anguilla)"),
    America_Antigua("America/Antigua","( GMT -4:00)Atlantic Standard Time(America/Antigua)"),
    America_Aruba("America/Aruba","( GMT -4:00)Atlantic Standard Time(America/Aruba)"),
    America_Asuncion("America/Asuncion","( GMT -4:00)Paraguay Time(America/Asuncion)"),
    America_Barbados("America/Barbados","( GMT -4:00)Atlantic Standard Time(America/Barbados)"),
    America_Boa_Vista("America/Boa_Vista","( GMT -4:00)Amazon Time(America/Boa_Vista)"),
    America_Campo_Grande("America/Campo_Grande","( GMT -4:00)Amazon Time(America/Campo_Grande)"),
    America_Cuiaba("America/Cuiaba","( GMT -4:00)Amazon Time(America/Cuiaba)"),
    America_Curacao("America/Curacao","( GMT -4:00)Atlantic Standard Time(America/Curacao)"),
    America_Dominica("America/Dominica","( GMT -4:00)Atlantic Standard Time(America/Dominica)"),
    America_Grenada("America/Grenada","( GMT -4:00)Atlantic Standard Time(America/Grenada)"),
    America_Guadeloupe("America/Guadeloupe","( GMT -4:00)Atlantic Standard Time(America/Guadeloupe)"),
    America_Guyana("America/Guyana","( GMT -4:00)Guyana Time(America/Guyana)"),
    America_Halifax("America/Halifax","( GMT -4:00)Atlantic Standard Time(America/Halifax)"),
    America_La_Paz("America/La_Paz","( GMT -4:00)Bolivia Time(America/La_Paz)"),
    America_Manaus("America/Manaus","( GMT -4:00)Amazon Time(America/Manaus)"),
    America_Martinique("America/Martinique","( GMT -4:00)Atlantic Standard Time(America/Martinique)"),
    America_Montserrat("America/Montserrat","( GMT -4:00)Atlantic Standard Time(America/Montserrat)"),
    America_Port_of_Spain("America/Port_of_Spain","( GMT -4:00)Atlantic Standard Time(America/Port_of_Spain)"),
    America_Porto_Velho("America/Porto_Velho","( GMT -4:00)Amazon Time(America/Porto_Velho)"),
    America_Puerto_Rico("America/Puerto_Rico","( GMT -4:00)Atlantic Standard Time(America/Puerto_Rico)"),
    America_Rio_Branco("America/Rio_Branco","( GMT -4:00)Amazon Time(America/Rio_Branco)"),
    America_Santiago("America/Santiago","( GMT -4:00)Chile Time(America/Santiago)"),
    America_Santo_Domingo("America/Santo_Domingo","( GMT -4:00)Atlantic Standard Time(America/Santo_Domingo)"),
    America_St_Kitts("America/St_Kitts","( GMT -4:00)Atlantic Standard Time(America/St_Kitts)"),
    America_St_Lucia("America/St_Lucia","( GMT -4:00)Atlantic Standard Time(America/St_Lucia)"),
    America_St_Thomas("America/St_Thomas","( GMT -4:00)Atlantic Standard Time(America/St_Thomas)"),
    America_St_Vincent("America/St_Vincent","( GMT -4:00)Atlantic Standard Time(America/St_Vincent)"),
    America_Thule("America/Thule","( GMT -4:00)Atlantic Standard Time(America/Thule)"),
    America_Tortola("America/Tortola","( GMT -4:00)Atlantic Standard Time(America/Tortola)"),
    Antarctica_Palmer("Antarctica/Palmer","( GMT -4:00)Chile Time(Antarctica/Palmer)"),
    Atlantic_Bermuda("Atlantic/Bermuda","( GMT -4:00)Atlantic Standard Time(Atlantic/Bermuda)"),
    America_St_Johns("America/St_Johns","( GMT -3:00)Newfoundland Standard Time(America/St_Johns)"),
    America_Araguaina("America/Araguaina","( GMT -3:00)Brasilia Time(America/Araguaina)"),
    America_Argentina_Buenos_Aires("America/Argentina/Buenos_Aires","( GMT -3:00)Argentine Time(America/Argentina/Buenos_Aires)"),
    America_Bahia("America/Bahia","( GMT -3:00)Brasilia Time(America/Bahia)"),
    America_Belem("America/Belem","( GMT -3:00)Brasilia Time(America/Belem)"),
    America_Cayenne("America/Cayenne","( GMT -3:00)French Guiana Time(America/Cayenne)"),
    America_Fortaleza("America/Fortaleza","( GMT -3:00)Brasilia Time(America/Fortaleza)"),
    America_Godthab("America/Godthab","( GMT -3:00)Western Greenland Time(America/Godthab)"),
    America_Maceio("America/Maceio","( GMT -3:00)Brasilia Time(America/Maceio)"),
    America_Miquelon("America/Miquelon","( GMT -3:00)Pierre & Miquelon Standard Time(America/Miquelon)"),
    America_Montevideo("America/Montevideo","( GMT -3:00)Uruguay Time(America/Montevideo)"),
    America_Paramaribo("America/Paramaribo","( GMT -3:00)Suriname Time(America/Paramaribo)"),
    America_Recife("America/Recife","( GMT -3:00)Brasilia Time(America/Recife)"),
    America_Sao_Paulo("America/Sao_Paulo","( GMT -3:00)Brasilia Time(America/Sao_Paulo)"),
    Antarctica_Rothera("Antarctica/Rothera","( GMT -3:00)Rothera Time(Antarctica/Rothera)"),
    Atlantic_Stanley("Atlantic/Stanley","( GMT -3:00)Falkland Is. Time(Atlantic/Stanley)"),
    America_Noronha("America/Noronha","( GMT -2:00)Fernando de Noronha Time(America/Noronha)"),
    Atlantic_South_Georgia("Atlantic/South_Georgia","( GMT -2:00)South Georgia Standard Time(Atlantic/South_Georgia)"),
    America_Scoresbysund("America/Scoresbysund","( GMT -1:00)Eastern Greenland Time(America/Scoresbysund)"),
    Atlantic_Azores("Atlantic/Azores","( GMT -1:00)Azores Time(Atlantic/Azores)"),
    Atlantic_Cape_Verde("Atlantic/Cape_Verde","( GMT -1:00)Cape Verde Time(Atlantic/Cape_Verde)"),
    Africa_Abidjan("Africa/Abidjan","( GMT 0:00)Greenwich Mean Time(Africa/Abidjan)"),
    Africa_Accra("Africa/Accra","( GMT 0:00)Ghana Mean Time(Africa/Accra)"),
    Africa_Bamako("Africa/Bamako","( GMT 0:00)Greenwich Mean Time(Africa/Bamako)"),
    Africa_Banjul("Africa/Banjul","( GMT 0:00)Greenwich Mean Time(Africa/Banjul)"),
    Africa_Bissau("Africa/Bissau","( GMT 0:00)Greenwich Mean Time(Africa/Bissau)"),
    Africa_Casablanca("Africa/Casablanca","( GMT 0:00)Western European Time(Africa/Casablanca)"),
    Africa_Conakry("Africa/Conakry","( GMT 0:00)Greenwich Mean Time(Africa/Conakry)"),
    Africa_Dakar("Africa/Dakar","( GMT 0:00)Greenwich Mean Time(Africa/Dakar)"),
    Africa_El_Aaiun("Africa/El_Aaiun","( GMT 0:00)Western European Time(Africa/El_Aaiun)"),
    Africa_Freetown("Africa/Freetown","( GMT 0:00)Greenwich Mean Time(Africa/Freetown)"),
    Africa_Lome("Africa/Lome","( GMT 0:00)Greenwich Mean Time(Africa/Lome)"),
    Africa_Monrovia("Africa/Monrovia","( GMT 0:00)Greenwich Mean Time(Africa/Monrovia)"),
    Africa_Nouakchott("Africa/Nouakchott","( GMT 0:00)Greenwich Mean Time(Africa/Nouakchott)"),
    Africa_Ouagadougou("Africa/Ouagadougou","( GMT 0:00)Greenwich Mean Time(Africa/Ouagadougou)"),
    Africa_Sao_Tome("Africa/Sao_Tome","( GMT 0:00)Greenwich Mean Time(Africa/Sao_Tome)"),
    America_Danmarkshavn("America/Danmarkshavn","( GMT 0:00)Greenwich Mean Time(America/Danmarkshavn)"),
    Atlantic_Canary("Atlantic/Canary","( GMT 0:00)Western European Time(Atlantic/Canary)"),
    Atlantic_Faroe("Atlantic/Faroe","( GMT 0:00)Western European Time(Atlantic/Faroe)"),
    Atlantic_Reykjavik("Atlantic/Reykjavik","( GMT 0:00)Greenwich Mean Time(Atlantic/Reykjavik)"),
    Atlantic_St_Helena("Atlantic/St_Helena","( GMT 0:00)Greenwich Mean Time(Atlantic/St_Helena)"),
    Etc_GMT("Etc/GMT","( GMT 0:00)GMT+00:00(Etc/GMT)"),
    Europe_Dublin("Europe/Dublin","( GMT 0:00)Greenwich Mean Time(Europe/Dublin)"),
    Europe_Lisbon("Europe/Lisbon","( GMT 0:00)Western European Time(Europe/Lisbon)"),
    Europe_London("Europe/London","( GMT 0:00)Greenwich Mean Time(Europe/London)"),
    Africa_Algiers("Africa/Algiers","( GMT 1:00)Central European Time(Africa/Algiers)"),
    Africa_Bangui("Africa/Bangui","( GMT 1:00)Western African Time(Africa/Bangui)"),
    Africa_Brazzaville("Africa/Brazzaville","( GMT 1:00)Western African Time(Africa/Brazzaville)"),
    Africa_Ceuta("Africa/Ceuta","( GMT 1:00)Central European Time(Africa/Ceuta)"),
    Africa_Douala("Africa/Douala","( GMT 1:00)Western African Time(Africa/Douala)"),
    Africa_Kinshasa("Africa/Kinshasa","( GMT 1:00)Western African Time(Africa/Kinshasa)"),
    Africa_Lagos("Africa/Lagos","( GMT 1:00)Western African Time(Africa/Lagos)"),
    Africa_Libreville("Africa/Libreville","( GMT 1:00)Western African Time(Africa/Libreville)"),
    Africa_Luanda("Africa/Luanda","( GMT 1:00)Western African Time(Africa/Luanda)"),
    Africa_Malabo("Africa/Malabo","( GMT 1:00)Western African Time(Africa/Malabo)"),
    Africa_Ndjamena("Africa/Ndjamena","( GMT 1:00)Western African Time(Africa/Ndjamena)"),
    Africa_Niamey("Africa/Niamey","( GMT 1:00)Western African Time(Africa/Niamey)"),
    Africa_Porto_Novo("Africa/Porto-Novo","( GMT 1:00)Western African Time(Africa/Porto-Novo)"),
    Africa_Tunis("Africa/Tunis","( GMT 1:00)Central European Time(Africa/Tunis)"),
    Africa_Windhoek("Africa/Windhoek","( GMT 1:00)Western African Time(Africa/Windhoek)"),
    Europe_Amsterdam("Europe/Amsterdam","( GMT 1:00)Central European Time(Europe/Amsterdam)"),
    Europe_Andorra("Europe/Andorra","( GMT 1:00)Central European Time(Europe/Andorra)"),
    Europe_Belgrade("Europe/Belgrade","( GMT 1:00)Central European Time(Europe/Belgrade)"),
    Europe_Berlin("Europe/Berlin","( GMT 1:00)Central European Time(Europe/Berlin)"),
    Europe_Brussels("Europe/Brussels","( GMT 1:00)Central European Time(Europe/Brussels)"),
    Europe_Budapest("Europe/Budapest","( GMT 1:00)Central European Time(Europe/Budapest)"),
    Europe_Copenhagen("Europe/Copenhagen","( GMT 1:00)Central European Time(Europe/Copenhagen)"),
    Europe_Gibraltar("Europe/Gibraltar","( GMT 1:00)Central European Time(Europe/Gibraltar)"),
    Europe_Luxembourg("Europe/Luxembourg","( GMT 1:00)Central European Time(Europe/Luxembourg)"),
    Europe_Madrid("Europe/Madrid","( GMT 1:00)Central European Time(Europe/Madrid)"),
    Europe_Malta("Europe/Malta","( GMT 1:00)Central European Time(Europe/Malta)"),
    Europe_Monaco("Europe/Monaco","( GMT 1:00)Central European Time(Europe/Monaco)"),
    Europe_Oslo("Europe/Oslo","( GMT 1:00)Central European Time(Europe/Oslo)"),
    Europe_Paris("Europe/Paris","( GMT 1:00)Central European Time(Europe/Paris)"),
    Europe_Prague("Europe/Prague","( GMT 1:00)Central European Time(Europe/Prague)"),
    Europe_Rome("Europe/Rome","( GMT 1:00)Central European Time(Europe/Rome)"),
    Europe_Stockholm("Europe/Stockholm","( GMT 1:00)Central European Time(Europe/Stockholm)"),
    Europe_Tirane("Europe/Tirane","( GMT 1:00)Central European Time(Europe/Tirane)"),
    Europe_Vaduz("Europe/Vaduz","( GMT 1:00)Central European Time(Europe/Vaduz)"),
    Europe_Vienna("Europe/Vienna","( GMT 1:00)Central European Time(Europe/Vienna)"),
    Europe_Warsaw("Europe/Warsaw","( GMT 1:00)Central European Time(Europe/Warsaw)"),
    Europe_Zurich("Europe/Zurich","( GMT 1:00)Central European Time(Europe/Zurich)"),
    Africa_Blantyre("Africa/Blantyre","( GMT 2:00)Central African Time(Africa/Blantyre)"),
    Africa_Bujumbura("Africa/Bujumbura","( GMT 2:00)Central African Time(Africa/Bujumbura)"),
    Africa_Cairo("Africa/Cairo","( GMT 2:00)Eastern European Time(Africa/Cairo)"),
    Africa_Gaborone("Africa/Gaborone","( GMT 2:00)Central African Time(Africa/Gaborone)"),
    Africa_Harare("Africa/Harare","( GMT 2:00)Central African Time(Africa/Harare)"),
    Africa_Johannesburg("Africa/Johannesburg","( GMT 2:00)South Africa Standard Time(Africa/Johannesburg)"),
    Africa_Kigali("Africa/Kigali","( GMT 2:00)Central African Time(Africa/Kigali)"),
    Africa_Lubumbashi("Africa/Lubumbashi","( GMT 2:00)Central African Time(Africa/Lubumbashi)"),
    Africa_Lusaka("Africa/Lusaka","( GMT 2:00)Central African Time(Africa/Lusaka)"),
    Africa_Maputo("Africa/Maputo","( GMT 2:00)Central African Time(Africa/Maputo)"),
    Africa_Maseru("Africa/Maseru","( GMT 2:00)South Africa Standard Time(Africa/Maseru)"),
    Africa_Mbabane("Africa/Mbabane","( GMT 2:00)South Africa Standard Time(Africa/Mbabane)"),
    Africa_Tripoli("Africa/Tripoli","( GMT 2:00)Eastern European Time(Africa/Tripoli)"),
    Asia_Amman("Asia/Amman","( GMT 2:00)Eastern European Time(Asia/Amman)"),
    Asia_Beirut("Asia/Beirut","( GMT 2:00)Eastern European Time(Asia/Beirut)"),
    Asia_Damascus("Asia/Damascus","( GMT 2:00)Eastern European Time(Asia/Damascus)"),
    Asia_Gaza("Asia/Gaza","( GMT 2:00)Eastern European Time(Asia/Gaza)"),
    Asia_Jerusalem("Asia/Jerusalem","( GMT 2:00)Israel Standard Time(Asia/Jerusalem)"),
    Asia_Nicosia("Asia/Nicosia","( GMT 2:00)Eastern European Time(Asia/Nicosia)"),
    Europe_Athens("Europe/Athens","( GMT 2:00)Eastern European Time(Europe/Athens)"),
    Europe_Bucharest("Europe/Bucharest","( GMT 2:00)Eastern European Time(Europe/Bucharest)"),
    Europe_Chisinau("Europe/Chisinau","( GMT 2:00)Eastern European Time(Europe/Chisinau)"),
    Europe_Helsinki("Europe/Helsinki","( GMT 2:00)Eastern European Time(Europe/Helsinki)"),
    Europe_Istanbul("Europe/Istanbul","( GMT 2:00)Eastern European Time(Europe/Istanbul)"),
    Europe_Kiev("Europe/Kiev","( GMT 2:00)Eastern European Time(Europe/Kiev)"),
    Europe_Riga("Europe/Riga","( GMT 2:00)Eastern European Time(Europe/Riga)"),
    Europe_Sofia("Europe/Sofia","( GMT 2:00)Eastern European Time(Europe/Sofia)"),
    Europe_Tallinn("Europe/Tallinn","( GMT 2:00)Eastern European Time(Europe/Tallinn)"),
    Europe_Vilnius("Europe/Vilnius","( GMT 2:00)Eastern European Time(Europe/Vilnius)"),
    Africa_Addis_Ababa("Africa/Addis_Ababa","( GMT 3:00)Eastern African Time(Africa/Addis_Ababa)"),
    Africa_Asmara("Africa/Asmara","( GMT 3:00)Eastern African Time(Africa/Asmara)"),
    Africa_Dar_es_Salaam("Africa/Dar_es_Salaam","( GMT 3:00)Eastern African Time(Africa/Dar_es_Salaam)"),
    Africa_Djibouti("Africa/Djibouti","( GMT 3:00)Eastern African Time(Africa/Djibouti)"),
    Africa_Kampala("Africa/Kampala","( GMT 3:00)Eastern African Time(Africa/Kampala)"),
    Africa_Khartoum("Africa/Khartoum","( GMT 3:00)Eastern African Time(Africa/Khartoum)"),
    Africa_Mogadishu("Africa/Mogadishu","( GMT 3:00)Eastern African Time(Africa/Mogadishu)"),
    Africa_Nairobi("Africa/Nairobi","( GMT 3:00)Eastern African Time(Africa/Nairobi)"),
    Antarctica_Syowa("Antarctica/Syowa","( GMT 3:00)Syowa Time(Antarctica/Syowa)"),
    Asia_Aden("Asia/Aden","( GMT 3:00)Arabia Standard Time(Asia/Aden)"),
    Asia_Baghdad("Asia/Baghdad","( GMT 3:00)Arabia Standard Time(Asia/Baghdad)"),
    Asia_Bahrain("Asia/Bahrain","( GMT 3:00)Arabia Standard Time(Asia/Bahrain)"),
    Asia_Kuwait("Asia/Kuwait","( GMT 3:00)Arabia Standard Time(Asia/Kuwait)"),
    Asia_Qatar("Asia/Qatar","( GMT 3:00)Arabia Standard Time(Asia/Qatar)"),
    Asia_Riyadh("Asia/Riyadh","( GMT 3:00)Arabia Standard Time(Asia/Riyadh)"),
    Europe_Kaliningrad("Europe/Kaliningrad","( GMT 3:00)Further-eastern European Time(Europe/Kaliningrad)"),
    Europe_Minsk("Europe/Minsk","( GMT 3:00)Further-eastern European Time(Europe/Minsk)"),
    Indian_Antananarivo("Indian/Antananarivo","( GMT 3:00)Eastern African Time(Indian/Antananarivo)"),
    Indian_Comoro("Indian/Comoro","( GMT 3:00)Eastern African Time(Indian/Comoro)"),
    Indian_Mayotte("Indian/Mayotte","( GMT 3:00)Eastern African Time(Indian/Mayotte)"),
    Asia_Tehran("Asia/Tehran","( GMT 3:00)Iran Standard Time(Asia/Tehran)"),
    Asia_Baku("Asia/Baku","( GMT 4:00)Azerbaijan Time(Asia/Baku)"),
    Asia_Dubai("Asia/Dubai","( GMT 4:00)Gulf Standard Time(Asia/Dubai)"),
    Asia_Muscat("Asia/Muscat","( GMT 4:00)Gulf Standard Time(Asia/Muscat)"),
    Asia_Tbilisi("Asia/Tbilisi","( GMT 4:00)Georgia Time(Asia/Tbilisi)"),
    Asia_Yerevan("Asia/Yerevan","( GMT 4:00)Armenia Time(Asia/Yerevan)"),
    Europe_Moscow("Europe/Moscow","( GMT 4:00)Moscow Standard Time(Europe/Moscow)"),
    Europe_Samara("Europe/Samara","( GMT 4:00)Samara Time(Europe/Samara)"),
    Indian_Mahe("Indian/Mahe","( GMT 4:00)Seychelles Time(Indian/Mahe)"),
    Indian_Mauritius("Indian/Mauritius","( GMT 4:00)Mauritius Time(Indian/Mauritius)"),
    Indian_Reunion("Indian/Reunion","( GMT 4:00)Reunion Time(Indian/Reunion)"),
    Asia_Kabul("Asia/Kabul","( GMT 4:00)Afghanistan Time(Asia/Kabul)"),
    Antarctica_Mawson("Antarctica/Mawson","( GMT 5:00)Mawson Time(Antarctica/Mawson)"),
    Asia_Aqtau("Asia/Aqtau","( GMT 5:00)Aqtau Time(Asia/Aqtau)"),
    Asia_Aqtobe("Asia/Aqtobe","( GMT 5:00)Aqtobe Time(Asia/Aqtobe)"),
    Asia_Ashgabat("Asia/Ashgabat","( GMT 5:00)Turkmenistan Time(Asia/Ashgabat)"),
    Asia_Dushanbe("Asia/Dushanbe","( GMT 5:00)Tajikistan Time(Asia/Dushanbe)"),
    Asia_Karachi("Asia/Karachi","( GMT 5:00)Pakistan Time(Asia/Karachi)"),
    Asia_Tashkent("Asia/Tashkent","( GMT 5:00)Uzbekistan Time(Asia/Tashkent)"),
    Indian_Kerguelen("Indian/Kerguelen","( GMT 5:00)French Southern & Antarctic Lands Time(Indian/Kerguelen)"),
    Indian_Maldives("Indian/Maldives","( GMT 5:00)Maldives Time(Indian/Maldives)"),
    Asia_Calcutta("Asia/Calcutta","( GMT 5:00)India Standard Time(Asia/Calcutta)"),
    Asia_Colombo("Asia/Colombo","( GMT 5:00)India Standard Time(Asia/Colombo)"),
    Asia_Katmandu("Asia/Katmandu","( GMT 5:00)Nepal Time(Asia/Katmandu)"),
    Antarctica_Vostok("Antarctica/Vostok","( GMT 6:00)Vostok Time(Antarctica/Vostok)"),
    Asia_Almaty("Asia/Almaty","( GMT 6:00)Alma-Ata Time(Asia/Almaty)"),
    Asia_Bishkek("Asia/Bishkek","( GMT 6:00)Kirgizstan Time(Asia/Bishkek)"),
    Asia_Dhaka("Asia/Dhaka","( GMT 6:00)Bangladesh Time(Asia/Dhaka)"),
    Asia_Thimphu("Asia/Thimphu","( GMT 6:00)Bhutan Time(Asia/Thimphu)"),
    Asia_Yekaterinburg("Asia/Yekaterinburg","( GMT 6:00)Yekaterinburg Time(Asia/Yekaterinburg)"),
    Indian_Chagos("Indian/Chagos","( GMT 6:00)Indian Ocean Territory Time(Indian/Chagos)"),
    Asia_Rangoon("Asia/Rangoon","( GMT 6:00)Myanmar Time(Asia/Rangoon)"),
    Indian_Cocos("Indian/Cocos","( GMT 6:00)Cocos Islands Time(Indian/Cocos)"),
    Antarctica_Davis("Antarctica/Davis","( GMT 7:00)Davis Time(Antarctica/Davis)"),
    Asia_Bangkok("Asia/Bangkok","( GMT 7:00)Indochina Time(Asia/Bangkok)"),
    Asia_Hovd("Asia/Hovd","( GMT 7:00)Hovd Time(Asia/Hovd)"),
    Asia_Jakarta("Asia/Jakarta","( GMT 7:00)West Indonesia Time(Asia/Jakarta)"),
    Asia_Omsk("Asia/Omsk","( GMT 7:00)Omsk Time(Asia/Omsk)"),
    Asia_Phnom_Penh("Asia/Phnom_Penh","( GMT 7:00)Indochina Time(Asia/Phnom_Penh)"),
    Asia_Saigon("Asia/Saigon","( GMT 7:00)Indochina Time(Asia/Saigon)"),
    Asia_Vientiane("Asia/Vientiane","( GMT 7:00)Indochina Time(Asia/Vientiane)"),
    Indian_Christmas("Indian/Christmas","( GMT 7:00)Christmas Island Time(Indian/Christmas)"),
    Antarctica_Casey("Antarctica/Casey","( GMT 8:00)Western Standard Time (Australia)(Antarctica/Casey)"),
    Asia_Brunei("Asia/Brunei","( GMT 8:00)Brunei Time(Asia/Brunei)"),
    Asia_Choibalsan("Asia/Choibalsan","( GMT 8:00)Choibalsan Time(Asia/Choibalsan)"),
    Asia_Hong_Kong("Asia/Hong_Kong","( GMT 8:00)Hong Kong Time(Asia/Hong_Kong)"),
    Asia_Krasnoyarsk("Asia/Krasnoyarsk","( GMT 8:00)Krasnoyarsk Time(Asia/Krasnoyarsk)"),
    Asia_Kuala_Lumpur("Asia/Kuala_Lumpur","( GMT 8:00)Malaysia Time(Asia/Kuala_Lumpur)"),
    Asia_Macau("Asia/Macau","( GMT 8:00)China Standard Time(Asia/Macau)"),
    Asia_Makassar("Asia/Makassar","( GMT 8:00)Central Indonesia Time(Asia/Makassar)"),
    Asia_Manila("Asia/Manila","( GMT 8:00)Philippines Time(Asia/Manila)"),
    Asia_Shanghai("Asia/Shanghai","( GMT 8:00)China Standard Time(Asia/Shanghai)"),
    Asia_Singapore("Asia/Singapore","( GMT 8:00)Singapore Time(Asia/Singapore)"),
    Asia_Taipei("Asia/Taipei","( GMT 8:00)China Standard Time(Asia/Taipei)"),
    Asia_Ulaanbaatar("Asia/Ulaanbaatar","( GMT 8:00)Ulaanbaatar Time(Asia/Ulaanbaatar)"),
    Australia_Perth("Australia/Perth","( GMT 8:00)Western Standard Time (Australia)(Australia/Perth)"),
    Asia_Dili("Asia/Dili","( GMT 9:00)Timor-Leste Time(Asia/Dili)"),
    Asia_Irkutsk("Asia/Irkutsk","( GMT 9:00)Irkutsk Time(Asia/Irkutsk)"),
    Asia_Jayapura("Asia/Jayapura","( GMT 9:00)East Indonesia Time(Asia/Jayapura)"),
    Asia_Pyongyang("Asia/Pyongyang","( GMT 9:00)Korea Standard Time(Asia/Pyongyang)"),
    Asia_Seoul("Asia/Seoul","( GMT 9:00)Korea Standard Time(Asia/Seoul)"),
    Asia_Tokyo("Asia/Tokyo","( GMT 9:00)Japan Standard Time(Asia/Tokyo)"),
    Pacific_Palau("Pacific/Palau","( GMT 9:00)Palau Time(Pacific/Palau)"),
    Australia_Adelaide("Australia/Adelaide","( GMT 9:00)Central Standard Time (South Australia)(Australia/Adelaide)"),
    Australia_Darwin("Australia/Darwin","( GMT 9:00)Central Standard Time (Northern Territory)(Australia/Darwin)"),
    Antarctica_DumontDUrville("Antarctica/DumontDUrville","( GMT 10:00)Dumont-d'Urville Time(Antarctica/DumontDUrville)"),
    Asia_Yakutsk("Asia/Yakutsk","( GMT 10:00)Yakutsk Time(Asia/Yakutsk)"),
    Australia_Brisbane("Australia/Brisbane","( GMT 10:00)Eastern Standard Time (Queensland)(Australia/Brisbane)"),
    Australia_Hobart("Australia/Hobart","( GMT 10:00)Eastern Standard Time (Tasmania)(Australia/Hobart)"),
    Australia_Sydney("Australia/Sydney","( GMT 10:00)Eastern Standard Time (New South Wales)(Australia/Sydney)"),
    Pacific_Guam("Pacific/Guam","( GMT 10:00)Chamorro Standard Time(Pacific/Guam)"),
    Pacific_Port_Moresby("Pacific/Port_Moresby","( GMT 10:00)Papua New Guinea Time(Pacific/Port_Moresby)"),
    Pacific_Saipan("Pacific/Saipan","( GMT 10:00)Chamorro Standard Time(Pacific/Saipan)"),
    Pacific_Truk("Pacific/Truk","( GMT 10:00)Chuuk Time(Pacific/Truk)"),
    Asia_Vladivostok("Asia/Vladivostok","( GMT 11:00)Vladivostok Time(Asia/Vladivostok)"),
    Pacific_Efate("Pacific/Efate","( GMT 11:00)Vanuatu Time(Pacific/Efate)"),
    Pacific_Guadalcanal("Pacific/Guadalcanal","( GMT 11:00)Solomon Is. Time(Pacific/Guadalcanal)"),
    Pacific_Kosrae("Pacific/Kosrae","( GMT 11:00)Kosrae Time(Pacific/Kosrae)"),
    Pacific_Noumea("Pacific/Noumea","( GMT 11:00)New Caledonia Time(Pacific/Noumea)"),
    Pacific_Ponape("Pacific/Ponape","( GMT 11:00)Pohnpei Time(Pacific/Ponape)"),
    Pacific_Norfolk("Pacific/Norfolk","( GMT 11:00)Norfolk Time(Pacific/Norfolk)"),
    Asia_Kamchatka("Asia/Kamchatka","( GMT 12:00)Petropavlovsk-Kamchatski Time(Asia/Kamchatka)"),
    Asia_Magadan("Asia/Magadan","( GMT 12:00)Magadan Time(Asia/Magadan)"),
    Pacific_Auckland("Pacific/Auckland","( GMT 12:00)New Zealand Standard Time(Pacific/Auckland)"),
    Pacific_Fiji("Pacific/Fiji","( GMT 12:00)Fiji Time(Pacific/Fiji)"),
    Pacific_Funafuti("Pacific/Funafuti","( GMT 12:00)Tuvalu Time(Pacific/Funafuti)"),
    Pacific_Kwajalein("Pacific/Kwajalein","( GMT 12:00)Marshall Islands Time(Pacific/Kwajalein)"),
    Pacific_Majuro("Pacific/Majuro","( GMT 12:00)Marshall Islands Time(Pacific/Majuro)"),
    Pacific_Nauru("Pacific/Nauru","( GMT 12:00)Nauru Time(Pacific/Nauru)"),
    Pacific_Tarawa("Pacific/Tarawa","( GMT 12:00)Gilbert Is. Time(Pacific/Tarawa)"),
    Pacific_Wake("Pacific/Wake","( GMT 12:00)Wake Time(Pacific/Wake)"),
    Pacific_Wallis("Pacific/Wallis","( GMT 12:00)Wallis & Futuna Time(Pacific/Wallis)"),
    Pacific_Enderbury("Pacific/Enderbury","( GMT 13:00)Phoenix Is. Time(Pacific/Enderbury)"),
    Pacific_Tongatapu("Pacific/Tongatapu","( GMT 13:00)Tonga Time(Pacific/Tongatapu)"),
    Pacific_Kiritimati("Pacific/Kiritimati","( GMT 14:00)Line Is. Time(Pacific/Kiritimati)");

    private String value;
    private String ID;
    TimeZoneSnow(String ID, String value) {
        this.ID = ID;
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public String getID(){
        return ID;
    }
}
