// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name snowApp.controller:CourseManageManagecontrollerCtrl
    * @description
    * # CourseManageManagecontrollerCtrl
    * Controller of the snowApp
   */
  angular.module('snowApp').controller('CourseManageManagecontrollerCtrl', function($scope, CourseManageCourseservice) {
    return CourseManageCourseservice.fetchRecentUpgradeCourses().then(function(data) {
      return $scope.recentUpgradeCourses = data;
    }, function(data) {});
  });

}).call(this);

//# sourceMappingURL=managecontroller.map
